# Generated by Django 4.2.7 on 2023-12-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pose', '0002_alter_post_options_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='detect_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
